name: Parallel
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "setup"
  job1:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"
  job2:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "job2"
  job3:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo "job3"
  end:
    needs: ["job1", "job2", "job3"]
    runs-on: ubuntu-latest
    steps:
      - run: echo "end"
